### ISSUE TITLE
Does not seem to load with the latest version of CE

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Better-Terrain-Addon#30]
I have MultiMC set up to swap in and swap out addons and versions, and this is the error I get on trying to play using this and the new CE release.

Better Than Wolves Community Edition Version 1.3.5 Initializing...
Better Than Wolves Initialization Complete.
Better Terrain Version 2.0.5 Initializing...
Exception in thread "main" java.lang.NoSuchMethodError: afn.addDesertBiome(Laav;)V
	at aav.<clinit>(BiomeGenBase.java:141)
	at BTABiomeConfiguration.<clinit>(BTABiomeConfiguration.java:125)
	at BTAMod.initWorldGen(BTAMod.java:42)
	at BTAMod.Initialize(BTAMod.java:30)
	at FCAddOnHandler.InitializeMods(FCAddOnHandler.java:69)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:308)
	at avv.<init>(SourceFile:38)
	at net.minecraft.client.MinecraftApplet.init(SourceFile:38)
	at net.minecraft.Launcher.init(Launcher.java:109)
	at org.multimc.LegacyFrame.start(LegacyFrame.java:130)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:131)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:240)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by ammoore00** [comment]
I've got an update almost ready to go to address this :) I've had a lot of IRL stuff that interrupted me being able to get an update out yet.

**Comment by AbbyRead** [comment]
No worries!  I'm excited to play all the new updates you put out.  Great work, Abby!
-Abby
